### PR TITLE
catch user errors in RAF callbacks (fixes #447)

### LINKED ISSUE #447: User space throw causes main loop termination
URL: `https://extent.network/user-space/user-space.html`

Crash when trying to run site in Exokit to emulate VR.

Running:
Ubuntu 18.04
Exokit 0.0.452

```
$ exokit https://extent.network/user-space/user-space.html 
THREE.WebGLRenderer 95
ReferenceError: name is not defined
    at requestUsers (server-connection.js:45:52)
    at update (user-space.js:97:5)
    at onAnimationFrame (js/three.js:22685:36)
    at onAnimationFrame (js/three.js:7424:4)
    at tickAnimationFrame (/usr/local/lib/exokit/core.js:691:9)
    at Timeout._recurse [as _onTimeout] (/usr/local/lib/exokit/index.js:1359:12)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)
Bugsnag:  Encountered an uncaught error, terminating…
ReferenceError: name is not defined
    at requestUsers (server-connection.js:45:52)
    at update (user-space.js:97:5)
    at onAnimationFrame (js/three.js:22685:36)
    at onAnimationFrame (js/three.js:7424:4)
    at tickAnimationFrame (/usr/local/lib/exokit/core.js:691:9)
    at Timeout._recurse [as _onTimeout] (/usr/local/lib/exokit/index.js:1359:12)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)
```

screenshot from 2018-09-09 19-40-40

### PR DESCRIPTION
**Pull request by ngokevin**

### CODE REVIEW

File: src/core.js [hunk 1]
```diff
@@ -676,7 +676,11 @@ function tickAnimationFrame() {
     for (let i = 0; i < localCbs.length; i++) {
       const rafCb = localCbs[i];
       if (rafCb && rafCb[symbols.windowSymbol].document.hidden) {
-        rafCb(performanceNow);
+        try {
+          rafCb(performanceNow);
+        } catch (e) {
+          console.error(e);
```
Comment (modulesio) [inline src/core.js]: Wondering if this should be `console.warn(e);`?

With `console.error(e)` in `node` I see this line here being output, which is not as useful as the actual user error.

Comment (ngokevin) [reply src/core.js]: Updated.
